#ifndef MAIN_H 
#define MAIN_H
#include "SDL2/SDL.h"
#include "SDL2/SDL_mixer.h"
#include "SDL2/SDL_image.h"
#include "SDL2/SDL_ttf.h"
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <math.h>
#include "elem.h"
#include "mov.h"
#include "coll.h"
#include "draw.h"
#include "map.h"
#endif MAIN_H
